/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/Button Switch.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Button Switch.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1983936034.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group114495047.geometry} material={materials.mat8} />
    </group>
  )
}

useGLTF.preload('/Button Switch.glb')
