/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/game.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/game.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Nintendo_DS.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/game.glb')
