/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/room.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat21} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat22} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat16} />
      <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat18} />
      <mesh geometry={nodes['Node-Mesh_4'].geometry} material={materials.mat15} />
      <mesh geometry={nodes['Node-Mesh_5'].geometry} material={materials.mat17} />
      <mesh geometry={nodes['Node-Mesh_6'].geometry} material={materials.mat19} />
      <mesh geometry={nodes['Node-Mesh_7'].geometry} material={materials.mat20} />
      <mesh geometry={nodes['Node-Mesh_8'].geometry} material={materials.mat3} />
      <mesh geometry={nodes['Node-Mesh_9'].geometry} material={materials.mat23} />
      <mesh geometry={nodes['Node-Mesh_10'].geometry} material={materials.mat24} />
      <mesh geometry={nodes['Node-Mesh_11'].geometry} material={materials.mat8} />
      <mesh geometry={nodes['Node-Mesh_12'].geometry} material={materials.mat12} />
      <mesh geometry={nodes['Node-Mesh_13'].geometry} material={materials.mat25} />
      <mesh geometry={nodes['Node-Mesh_14'].geometry} material={materials.mat9} />
      <mesh geometry={nodes['Node-Mesh_15'].geometry} material={materials.mat14} />
      <mesh geometry={nodes['Node-Mesh_16'].geometry} material={materials.mat7} />
      <mesh geometry={nodes['Node-Mesh_17'].geometry} material={materials.mat5} />
    </group>
  )
}

useGLTF.preload('/room.glb')
