/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/block.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Block(props) {
  const { nodes, materials } = useGLTF('models/block.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh1747336890.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1747336890_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1747336890_2.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh572745584.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh572745584_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1749781905.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1749781905_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh276336442.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh276336442_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1290640350.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1290640350_1.geometry} material={materials.mat22} />
    </group>
  )
}

useGLTF.preload('models/block.glb')
