/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Book(props) {
  const { nodes, materials } = useGLTF('models/Notebook.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.042']}
        position={[0, 0.282, 0]}
        scale={[0.993, 0.281, 1.628]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Material.043']}
        position={[-0.066, 0.274, -0.004]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.178, -1.505]}
      />
    </group>
  )
}

useGLTF.preload('models/Notebook.glb')
