/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/book.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Book(props) {
  const { nodes, materials } = useGLTF('models/book.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group2054475742.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1074715379.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group864524524.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group302886228.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group2106157651.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group890815322.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1366704648.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group205953448.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1055530063.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1821933033.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group625863372.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1787463791.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group354335200.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group318023108.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1401441398.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1503053929.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group754680489.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1561494337.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group112102897.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1818783783.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1770968833.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1991508254.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1867008514.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1980743097.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1137347155.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1136578913.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group577591582.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1175376283.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group885303643.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1616838820.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1675552867.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group227602719.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1155450240.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group636680026.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1001704908.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1266326714.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1918276341.geometry} material={materials.mat19} />
    </group>
  )
}

useGLTF.preload('models/book.glb')
