/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/computer.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Computer(props) {
  const { nodes, materials } = useGLTF('models/computer.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mousepad001.geometry} material={materials['Mousepad.001']} position={[0, 2.982, 0.013]} rotation={[-Math.PI / 2, 0, 0]} scale={[377.753, 159.159, 1.322]} />
      <mesh geometry={nodes.Mouse.geometry} material={materials['Material.038']} position={[1.962, 3.002, 0.854]} scale={482.648} />
      <group position={[0.389, 4.008, -0.23]} rotation={[Math.PI / 2, 0, 0]} scale={[1.402, 0.622, 0.697]}>
        <mesh geometry={nodes.Plane012.geometry} material={materials['Material.026']} />
        <mesh geometry={nodes.Plane012_1.geometry} material={materials['Material.027']} />
      </group>
      <mesh geometry={nodes.screen.geometry} material={materials['Material.028']} position={[0.389, 4.008, -0.224]} rotation={[Math.PI / 2, 0, 0]} scale={[1.402, 0.622, 0.697]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.009']} position={[3.669, 1.506, -1.412]} scale={[0.191, 1.452, 0.185]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.012']} position={[3.7, 1.501, 1.497]} scale={[0.191, 1.452, 0.185]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.011']} position={[-3.709, 1.51, -1.42]} scale={[0.191, 1.452, 0.185]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.013']} position={[-3.709, 1.505, 1.515]} scale={[0.191, 1.452, 0.185]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.002']} position={[0, 2.752, 0.033]} scale={[3.984, 0.216, 1.749]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.037']} position={[0.332, 3.016, 0.854]} scale={[0.775, 0.302, 0.298]} />
      <mesh geometry={nodes.Cube029.geometry} material={materials['Material.036']} position={[-0.366, 3.02, 0.653]} scale={[0.035, 0.006, 0.032]} />
      <mesh geometry={nodes.screen001.geometry} material={materials['Material.032']} position={[-2.049, 4.008, 0.76]} rotation={[Math.PI / 2, 0, -0.843]} scale={[1.402, 0.622, 0.697]} />
      <group position={[-2.054, 4.008, 0.755]} rotation={[Math.PI / 2, 0, -0.843]} scale={[1.402, 0.622, 0.697]}>
        <mesh geometry={nodes.Plane017.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Plane017_1.geometry} material={materials['Material.033']} />
      </group>
      <mesh geometry={nodes.Computer.geometry} material={materials['Material.035']} position={[3.335, 3.022, 0.165]} scale={486.497} />
    </group>
  )
}

useGLTF.preload('models/computer.glb')
