/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/table.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Desk(props) {
  const { nodes, materials } = useGLTF('models/table.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.006']} position={[3.669, 1.467, -1.221]} scale={[0.191, 1.452, 0.185]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.001']} position={[0, 2.767, 0]} scale={[3.984, 0.213, 1.463]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.004']} position={[-3.709, 1.467, -1.221]} scale={[0.191, 1.452, 0.185]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.002']} position={[3.7, 1.467, 1.197]} scale={[0.191, 1.452, 0.185]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.005']} position={[-3.709, 1.467, 1.197]} scale={[0.191, 1.452, 0.185]} />

    
    </group>
  )
}

useGLTF.preload('models/table.glb')
