/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/Nintendo Switch.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Project1(props) {
  const { nodes, materials } = useGLTF('models/Nintendo Switch.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Cube-Mesh'].geometry} material={materials['Material.003']} />
      <mesh geometry={nodes['Cube-Mesh_1'].geometry} material={materials['Material.004']} />
      <mesh geometry={nodes['Cube-Mesh_2'].geometry} material={materials['Material.006']} />
    </group>
  )
}

useGLTF.preload('models/Nintendo Switch.glb')
